<?php

namespace App\DataFixture;

use App\Entity\Base\AbstractEntity;
use App\Entity\Final\Character;
use App\Entity\Final\Element;
use App\Entity\Final\Region;
use App\Entity\Final\WeaponCategory;
use App\Enum\Genre;
use App\Enum\Size;
use App\Service\Entity\Final\CharacterManager;
use DateTimeImmutable;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Exception;

/**
 * @template-extends AbstractFixtures<Character>
 */
class CharacterFixtures extends AbstractFixtures implements DependentFixtureInterface {

    public function __construct(CharacterManager $entityManager) {
        parent::__construct($entityManager);
    }

    /**
     * @return class-string[]
     */
    public function getDependencies(): array {
        return [ElementFixtures::class, WeaponCategoryFixtures::class, RegionFixtures::class];
    }

    protected function getEntityInfos(): array {
        return [
            [
                'name'           => 'Amber',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Bow',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Barbara',
                'rare'           => false,
                'element'        => 'Hydro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Beidou',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Bennett',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Sword',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Chongyun',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Claymore',
                'region'         => 'Liyue',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Diluc',
                'rare'           => true,
                'element'        => 'Pyro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Fischl',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Bow',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Jean',
                'rare'           => true,
                'element'        => 'Anemo',
                'weaponCategory' => 'Sword',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Kaeya',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Sword',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Keqing',
                'rare'           => true,
                'element'        => 'Electro',
                'weaponCategory' => 'Sword',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Lisa',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Mona',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Ningguang',
                'rare'           => false,
                'element'        => 'Geo',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Noelle',
                'rare'           => false,
                'element'        => 'Geo',
                'weaponCategory' => 'Claymore',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Qiqi',
                'rare'           => true,
                'element'        => 'Cryo',
                'weaponCategory' => 'Sword',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Razor',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Sucrose',
                'rare'           => false,
                'element'        => 'Anemo',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Venti',
                'rare'           => true,
                'element'        => 'Anemo',
                'weaponCategory' => 'Bow',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Xiangling',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Xingqiu',
                'rare'           => false,
                'element'        => 'Hydro',
                'weaponCategory' => 'Sword',
                'region'         => 'Liyue',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-09-28',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Klee',
                'rare'           => true,
                'element'        => 'Pyro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2020-10-20',
                'version'        => '1.0',
            ],
            [
                'name'           => 'Diona',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Bow',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2020-11-11',
                'version'        => '1.1',
            ],
            [
                'name'           => 'Tartaglia',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Bow',
                'region'         => 'Snezhnaya',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-11-11',
                'version'        => '1.1',
            ],
            [
                'name'           => 'Xinyan',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-12-01',
                'version'        => '1.1',
            ],
            [
                'name'           => 'Zhongli',
                'rare'           => true,
                'element'        => 'Geo',
                'weaponCategory' => 'Polearm',
                'region'         => 'Liyue',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2020-12-01',
                'version'        => '1.1',
            ],
            [
                'name'           => 'Albedo',
                'rare'           => true,
                'element'        => 'Geo',
                'weaponCategory' => 'Sword',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2020-12-23',
                'version'        => '1.2',
            ],
            [
                'name'           => 'Ganyu',
                'rare'           => true,
                'element'        => 'Cryo',
                'weaponCategory' => 'Bow',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-01-12',
                'version'        => '1.2',
            ],
            [
                'name'           => 'Xiao',
                'rare'           => true,
                'element'        => 'Anemo',
                'weaponCategory' => 'Polearm',
                'region'         => 'Liyue',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-02-03',
                'version'        => '1.3',
            ],
            [
                'name'           => 'Hu Tao',
                'rare'           => true,
                'element'        => 'Pyro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-03-02',
                'version'        => '1.3',
            ],
            [
                'name'           => 'Rosaria',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Polearm',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2021-04-06',
                'version'        => '1.4',
            ],
            [
                'name'           => 'Yanfei',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-04-28',
                'version'        => '1.5',
            ],
            [
                'name'           => 'Eula',
                'rare'           => true,
                'element'        => 'Cryo',
                'weaponCategory' => 'Claymore',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2021-05-18',
                'version'        => '1.5',
            ],
            [
                'name'           => 'Kaedehara Kazuha',
                'rare'           => true,
                'element'        => 'Anemo',
                'weaponCategory' => 'Sword',
                'region'         => 'Inazuma',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-06-29',
                'version'        => '1.6',
            ],
            [
                'name'           => 'Kamisato Ayaka',
                'rare'           => true,
                'element'        => 'Cryo',
                'weaponCategory' => 'Sword',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-07-21',
                'version'        => '2.0',
            ],
            [
                'name'           => 'Sayu',
                'rare'           => false,
                'element'        => 'Anemo',
                'weaponCategory' => 'Claymore',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2021-08-10',
                'version'        => '2.0',
            ],
            [
                'name'           => 'Yoimiya',
                'rare'           => true,
                'element'        => 'Pyro',
                'weaponCategory' => 'Bow',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-08-10',
                'version'        => '2.0',
            ],
            [
                'name'           => 'Aloy',
                'rare'           => true,
                'element'        => 'Cryo',
                'weaponCategory' => 'Bow',
                'region'         => 'None',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-09-01',
                'version'        => '2.1',
            ],
            [
                'name'           => 'Kujou Sara',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Bow',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2021-09-01',
                'version'        => '2.1',
            ],
            [
                'name'           => 'Raiden Shogun',
                'rare'           => true,
                'element'        => 'Electro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2021-09-01',
                'version'        => '2.1',
            ],
            [
                'name'           => 'Sangonomiya Kokomi',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-09-21',
                'version'        => '2.1',
            ],
            [
                'name'           => 'Thoma',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Inazuma',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2021-11-02',
                'version'        => '2.2',
            ],
            [
                'name'           => 'Arataki Itto',
                'rare'           => true,
                'element'        => 'Geo',
                'weaponCategory' => 'Claymore',
                'region'         => 'Inazuma',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2021-12-14',
                'version'        => '2.3',
            ],
            [
                'name'           => 'Gorou',
                'rare'           => false,
                'element'        => 'Geo',
                'weaponCategory' => 'Bow',
                'region'         => 'Inazuma',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2021-12-14',
                'version'        => '2.3',
            ],
            [
                'name'           => 'Shenhe',
                'rare'           => true,
                'element'        => 'Cryo',
                'weaponCategory' => 'Polearm',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2022-01-05',
                'version'        => '2.4',
            ],
            [
                'name'           => 'Yun Jin',
                'rare'           => false,
                'element'        => 'Geo',
                'weaponCategory' => 'Polearm',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-01-05',
                'version'        => '2.4',
            ],
            [
                'name'           => 'Yae Miko',
                'rare'           => true,
                'element'        => 'Electro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2022-02-16',
                'version'        => '2.5',
            ],
            [
                'name'           => 'Kamisato Ayato',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Sword',
                'region'         => 'Inazuma',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2022-03-30',
                'version'        => '2.6',
            ],
            [
                'name'           => 'Yelan',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Bow',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2022-05-31',
                'version'        => '2.7',
            ],
            [
                'name'           => 'Kuki Shinobu',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Sword',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-06-21',
                'version'        => '2.7',
            ],
            [
                'name'           => 'Shikanoin Heizou',
                'rare'           => false,
                'element'        => 'Anemo',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Inazuma',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-07-13',
                'version'        => '2.8',
            ],
            [
                'name'           => 'Collei',
                'rare'           => false,
                'element'        => 'Dendro',
                'weaponCategory' => 'Bow',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-08-24',
                'version'        => '3.0',
            ],
            [
                'name'           => 'Tighnari',
                'rare'           => true,
                'element'        => 'Dendro',
                'weaponCategory' => 'Bow',
                'region'         => 'Sumeru',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-08-24',
                'version'        => '3.0',
            ],
            [
                'name'           => 'Dori',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2022-09-09',
                'version'        => '3.0',
            ],
            [
                'name'           => 'Candace',
                'rare'           => false,
                'element'        => 'Hydro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2022-09-28',
                'version'        => '3.1',
            ],
            [
                'name'           => 'Cyno',
                'rare'           => true,
                'element'        => 'Electro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Sumeru',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-09-28',
                'version'        => '3.1',
            ],
            [
                'name'           => 'Nilou',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Sword',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-10-14',
                'version'        => '3.1',
            ],
            [
                'name'           => 'Nahida',
                'rare'           => true,
                'element'        => 'Dendro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2022-11-02',
                'version'        => '3.2',
            ],
            [
                'name'           => 'Layla',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Sword',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-11-18',
                'version'        => '3.2',
            ],
            [
                'name'           => 'Faruzan',
                'rare'           => false,
                'element'        => 'Anemo',
                'weaponCategory' => 'Bow',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-12-07',
                'version'        => '3.3',
            ],
            [
                'name'           => 'Wanderer',
                'rare'           => true,
                'element'        => 'Anemo',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Sumeru',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2022-12-07',
                'version'        => '3.3',
            ],
            [
                'name'           => 'Alhaitham',
                'rare'           => true,
                'element'        => 'Dendro',
                'weaponCategory' => 'Sword',
                'region'         => 'Sumeru',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2023-01-18',
                'version'        => '3.4',
            ],
            [
                'name'           => 'Yaoyao',
                'rare'           => false,
                'element'        => 'Dendro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2023-01-18',
                'version'        => '3.4',
            ],
            [
                'name'           => 'Dehya',
                'rare'           => true,
                'element'        => 'Pyro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Sumeru',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2023-03-01',
                'version'        => '3.5',
            ],
            [
                'name'           => 'Mika',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Polearm',
                'region'         => 'Mondstadt',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2023-03-21',
                'version'        => '3.5',
            ],
            [
                'name'           => 'Baizhu',
                'rare'           => true,
                'element'        => 'Dendro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Liyue',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2023-05-02',
                'version'        => '3.6',
            ],
            [
                'name'           => 'Kaveh',
                'rare'           => false,
                'element'        => 'Dendro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Sumeru',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2023-05-02',
                'version'        => '3.6',
            ],
            [
                'name'           => 'Kirara',
                'rare'           => false,
                'element'        => 'Dendro',
                'weaponCategory' => 'Sword',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2023-05-24',
                'version'        => '3.7',
            ],
            [
                'name'           => 'Lynette',
                'rare'           => false,
                'element'        => 'Anemo',
                'weaponCategory' => 'Sword',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2023-08-16',
                'version'        => '4.0',
            ],
            [
                'name'           => 'Lyney',
                'rare'           => true,
                'element'        => 'Pyro',
                'weaponCategory' => 'Bow',
                'region'         => 'Fontaine',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2023-08-16',
                'version'        => '4.0',
            ],
            [
                'name'           => 'Freminet',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Claymore',
                'region'         => 'Fontaine',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2023-09-05',
                'version'        => '4.0',
            ],
            [
                'name'           => 'Neuvillette',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Fontaine',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2023-09-27',
                'version'        => '4.1',
            ],
            [
                'name'           => 'Wriothesley',
                'rare'           => true,
                'element'        => 'Cryo',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Fontaine',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2023-10-17',
                'version'        => '4.1',
            ],
            [
                'name'           => 'Charlotte',
                'rare'           => false,
                'element'        => 'Cryo',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2023-11-08',
                'version'        => '4.2',
            ],
            [
                'name'           => 'Furina',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Sword',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2023-11-08',
                'version'        => '4.2',
            ],
            [
                'name'           => 'Navia',
                'rare'           => true,
                'element'        => 'Geo',
                'weaponCategory' => 'Claymore',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2023-12-20',
                'version'        => '4.3',
            ],
            [
                'name'           => 'Chevreuse',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2024-01-09',
                'version'        => '4.3',
            ],
            [
                'name'           => 'Gaming',
                'rare'           => false,
                'element'        => 'Pyro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Liyue',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2024-01-31',
                'version'        => '4.4',
            ],
            [
                'name'           => 'Xianyun',
                'rare'           => true,
                'element'        => 'Anemo',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Liyue',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2024-01-31',
                'version'        => '4.4',
            ],
            [
                'name'           => 'Chiori',
                'rare'           => true,
                'element'        => 'Geo',
                'weaponCategory' => 'Sword',
                'region'         => 'Inazuma',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2024-03-13',
                'version'        => '4.5',
            ],
            [
                'name'           => 'Arlecchino',
                'rare'           => true,
                'element'        => 'Pyro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Snezhnaya',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2024-04-24',
                'version'        => '4.6',
            ],
            [
                'name'           => 'Clorinde',
                'rare'           => true,
                'element'        => 'Electro',
                'weaponCategory' => 'Sword',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2024-06-05',
                'version'        => '4.7',
            ],
            [
                'name'           => 'Sethos',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Bow',
                'region'         => 'Sumeru',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2024-06-05',
                'version'        => '4.7',
            ],
            [
                'name'           => 'Sigewinne',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Bow',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2024-06-25',
                'version'        => '4.7',
            ],
            [
                'name'           => 'Emilie',
                'rare'           => true,
                'element'        => 'Dendro',
                'weaponCategory' => 'Polearm',
                'region'         => 'Fontaine',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2024-08-06',
                'version'        => '4.8',
            ],
            [
                'name'           => 'Kachina',
                'rare'           => false,
                'element'        => 'Geo',
                'weaponCategory' => 'Polearm',
                'region'         => 'Natlan',
                'genre'          => Genre::Female,
                'size'           => Size::Short,
                'releaseDate'    => '2024-08-28',
                'version'        => '5.0',
            ],
            [
                'name'           => 'Mualani',
                'rare'           => true,
                'element'        => 'Hydro',
                'weaponCategory' => 'Catalyst',
                'region'         => 'Natlan',
                'genre'          => Genre::Female,
                'size'           => Size::Medium,
                'releaseDate'    => '2024-08-28',
                'version'        => '5.0',
            ],
            [
                'name'           => 'Kinich',
                'rare'           => true,
                'element'        => 'Dendro',
                'weaponCategory' => 'Claymore',
                'region'         => 'Natlan',
                'genre'          => Genre::Male,
                'size'           => Size::Medium,
                'releaseDate'    => '2024-09-17',
                'version'        => '5.0',
            ],
            [
                'name'           => 'Xilonen',
                'rare'           => true,
                'element'        => 'Geo',
                'weaponCategory' => 'Sword',
                'region'         => 'Natlan',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2024-10-09',
                'version'        => '5.1',
            ],
            [
                'name'           => 'Chasca',
                'rare'           => true,
                'element'        => 'Anemo',
                'weaponCategory' => 'Bow',
                'region'         => 'Natlan',
                'genre'          => Genre::Female,
                'size'           => Size::Tall,
                'releaseDate'    => '2024-11-20',
                'version'        => '5.2',
            ],
            [
                'name'           => 'Ororon',
                'rare'           => false,
                'element'        => 'Electro',
                'weaponCategory' => 'Bow',
                'region'         => 'Natlan',
                'genre'          => Genre::Male,
                'size'           => Size::Tall,
                'releaseDate'    => '2024-11-20',
                'version'        => '5.2',
            ],
        ];
    }

    /**
     * @param Character            $entity
     * @param array<string, mixed> $entityInfo
     *
     * @return void
     * @throws Exception
     */
    protected function hydrateEntity(AbstractEntity $entity, array $entityInfo): void {
        $entity
            ->setName($entityInfo['name'])
            ->setRare($entityInfo['rare'])
            ->setElement($this->getEntityReference(Element::class, $entityInfo['element']))
            ->setWeaponCategory($this->getEntityReference(WeaponCategory::class, $entityInfo['weaponCategory']))
            ->setRegion($this->getEntityReference(Region::class, $entityInfo['region']))
            ->setGenre($entityInfo['genre'])
            ->setSize($entityInfo['size'])
            ->setReleaseDate(new DateTimeImmutable($entityInfo['releaseDate']))
            ->setVersion($entityInfo['version']);
    }

}
