<?php

namespace App\Constant;

class ValidationGroup {

    const DEFAULT       = 'Default';
    const AUTOGENERATED = 'Autogenerated';
    const SECRET        = 'Secret';

    const NOT_SECRET = [self::DEFAULT, self::AUTOGENERATED];
    const ALL        = [self::DEFAULT, self::AUTOGENERATED, self::SECRET];

}